/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrdrecruitment;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author Galih Dea
 */
public class lihatNilai extends javax.swing.JFrame {

    /**
     * Creates new form lihatNilai
     */
    public lihatNilai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        divisi = new javax.swing.JComboBox<>();
        lihat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelNilai = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelGap = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelRank = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        kesimpulan = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clarian.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Divisi :");

        divisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Site Management", "Masterbatch Plant", "Pigment Plant", "Site ESHA", "Warehouse and Transportation", "Site Admin", "Black Belt", "EXIM", "Operation", "Maintenance", "W.W Treatment", "ICS MPP", "Production Planning", "Quality Control", " " }));
        divisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisiActionPerformed(evt);
            }
        });

        lihat.setText("Lihat");
        lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatActionPerformed(evt);
            }
        });

        tabelNilai.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabelNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "NIK", "Nama", "Jabatan", "Konsentrasi", "Fleksibilitas", "Antisipasi", "Penalaran", "Kreatifitas", "Potensi IQ", "Energi Psikis", "Ketelitian", "Pengendalian", "Motivasi", "Kehati-hatian", "Kesopanan", "Kepedulian", "Ketaatan", "Ego", "Proaktif", "Super Ego"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelNilai.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelNilai.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelNilai);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tabel Nilai");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabelGap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "NIK", "Nama", "Jabatan", "NCI", "NSI", "NI", "NCSK", "NSSK", "NSK", "NCP", "NSP", "NP", "HA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelGap.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(tabelGap);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tabel Nilai Total");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tabel Ranking");

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabelRank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "NIK", "Nama", "Jabatan", "Skor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelRank.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(tabelRank);

        kesimpulan.setColumns(20);
        kesimpulan.setRows(5);
        jScrollPane4.setViewportView(kesimpulan);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Kesimpulan");

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel7.setText("HASIL PENILAIAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(561, 561, 561))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(divisi, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lihat)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(380, 380, 380))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(divisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lihat)
                    .addComponent(jLabel7))
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kembali, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatActionPerformed
        // TODO add your handling code here:
        String divi = (String)divisi.getSelectedItem();
        int baris = 0;
        try{
            String que = "";
            //DefaultTableModel tbl = new DefaultTableModel();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hrd","root","");
            Statement stmt = con.createStatement();
            if(divi.equals("Semua")){
                que = "select * from karyawan";
            }
            else{
                que = "select * from karyawan WHERE divisi='"+divi+"'";
            }
            ResultSet rs = stmt.executeQuery(que);
            while(rs.next()){
                //tabelKaryawan.setValueAt();
                baris++;
            }
            con.close();
        }
        catch(Exception e){
            System.out.println(e);
        }
        DefaultTableModel tbl1 = (DefaultTableModel)tabelNilai.getModel();
        DefaultTableModel tbl2 = (DefaultTableModel)tabelGap.getModel();
        DefaultTableModel tbl3 = (DefaultTableModel)tabelRank.getModel();
        tbl1.setRowCount(baris);
        tbl2.setRowCount(baris);
        tbl3.setRowCount(baris);
        int i = 0;
        double[] NCi = new double[baris];
        double[] NSi = new double[baris];
        double[] Ni = new double[baris];
        double[] NCsk = new double[baris];
        double[] NSsk = new double[baris];
        double[] Nsk = new double[baris];
        double[] NCp = new double[baris];
        double[] NSp = new double[baris];
        double[] Npe = new double[baris];
        double[] Ha = new double[baris];
        try{
            String que = "";
            //DefaultTableModel tbl = new DefaultTableModel();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hrd","root","");
            Statement stmt = con.createStatement();
            if(divi.equals("Semua")){
                que = "select * from karyawan";
            }
            else{
                que = "select * from karyawan WHERE divisi='"+divi+"'";
            }
            ResultSet rs = stmt.executeQuery(que);
            while(rs.next()){
                int j = i+1;
                System.out.println(rs.getString(2)+","+rs.getString(3)+","+rs.getInt(4)+","+rs.getString(5)+","+rs.getString(6));
                tbl1.setValueAt((Object)j,i,0);
                tbl1.setValueAt((Object)rs.getString(2),i,1);
                tbl1.setValueAt((Object)rs.getString(3),i,2);
                tbl1.setValueAt((Object)rs.getString(6),i,3);
                tbl1.setValueAt((Object)rs.getInt(7),i,4);
                tbl1.setValueAt((Object)rs.getInt(8),i,5);
                tbl1.setValueAt((Object)rs.getInt(9),i,6);
                tbl1.setValueAt((Object)rs.getInt(10),i,7);
                tbl1.setValueAt((Object)rs.getInt(11),i,8);
                tbl1.setValueAt((Object)rs.getInt(12),i,9);
                tbl1.setValueAt((Object)rs.getInt(13),i,10);
                tbl1.setValueAt((Object)rs.getInt(14),i,11);
                tbl1.setValueAt((Object)rs.getInt(15),i,12);
                tbl1.setValueAt((Object)rs.getInt(16),i,13);
                tbl1.setValueAt((Object)rs.getInt(17),i,14);
                tbl1.setValueAt((Object)rs.getInt(18),i,15);
                tbl1.setValueAt((Object)rs.getInt(19),i,16);
                tbl1.setValueAt((Object)rs.getInt(20),i,17);
                tbl1.setValueAt((Object)rs.getInt(21),i,18);
                tbl1.setValueAt((Object)rs.getInt(22),i,19);
                tbl1.setValueAt((Object)rs.getInt(23),i,20);
                tbl2.setValueAt((Object)j,i,0);
                tbl2.setValueAt((Object)rs.getString(2),i,1);
                tbl2.setValueAt((Object)rs.getString(3),i,2);
                tbl2.setValueAt((Object)rs.getString(6),i,3);
                NCi[i] = (double)(rs.getInt(7)+rs.getInt(8)+rs.getInt(9))/3;
                NSi[i] = (double)(rs.getInt(10)+rs.getInt(11)+rs.getInt(12))/3;
                Ni[i] = (rs.getDouble(24)*NCi[i])+(rs.getDouble(25)*NSi[i]);
                NCsk[i] = (double)(rs.getInt(13)+rs.getInt(14)+rs.getInt(15))/3;
                NSsk[i] = (double)(rs.getInt(16)+rs.getInt(17))/2;
                Nsk[i] = (rs.getDouble(27)*NCsk[i])+(rs.getDouble(28)*NSsk[i]);
                NCp[i] = (double)(rs.getInt(18)+rs.getInt(19)+rs.getInt(20))/3;
                NSp[i] = (double)(rs.getInt(21)+rs.getInt(22)+rs.getInt(23))/3;
                Npe[i] = (rs.getDouble(30)*NCp[i])+(rs.getDouble(31)*NSp[i]);
                Ha[i] = (rs.getDouble(26)*Ni[i])+(rs.getDouble(29)*Nsk[i])+(rs.getDouble(32)*Npe[i]);
                tbl2.setValueAt((Object)NCi[i], i, 4);
                tbl2.setValueAt((Object)NSi[i], i, 5);
                tbl2.setValueAt((Object)Ni[i], i, 6);
                tbl2.setValueAt((Object)NCsk[i], i, 7);
                tbl2.setValueAt((Object)NSsk[i], i, 8);
                tbl2.setValueAt((Object)Nsk[i], i, 9);
                tbl2.setValueAt((Object)NCp[i], i, 10);
                tbl2.setValueAt((Object)NSp[i], i, 11);
                tbl2.setValueAt((Object)Npe[i], i, 12);
                tbl2.setValueAt((Object)Ha[i], i, 13);
                i++;
            }
            tabelNilai.setModel(tbl1);
            tabelGap.setModel(tbl2);
            String tempnik,tempnama,tempjab;
            double temprank;
            String[] nikurut = new String[baris];
            String[] namaurut = new String[baris];
            String[] jaburut = new String[baris];
            double[] rank = new double[baris];
            for(i=0;i<baris;i++){
                nikurut[i] = (String)tabelNilai.getModel().getValueAt(i,1);
                namaurut[i] = (String)tabelNilai.getModel().getValueAt(i,2);
                jaburut[i] = (String)tabelNilai.getModel().getValueAt(i,3);
                rank[i] = Ha[i];
            }
            for(i=0;i<baris-1;i++){
                int idxmax = i;
                int j;
                for(j=i;j<baris;j++){
                    if(rank[j]>rank[idxmax]){
                        idxmax = j;
                    }
                }
                temprank = rank[i];
                rank[i] = rank[idxmax];
                rank[idxmax] = temprank;
                tempnik = nikurut[i];
                nikurut[i] = nikurut[idxmax];
                nikurut[idxmax] = tempnik;
                tempnama = namaurut[i];
                namaurut[i] = namaurut[idxmax];
                namaurut[idxmax] = tempnama;
                tempjab = jaburut[i];
                jaburut[i] = jaburut[idxmax];
                jaburut[idxmax] = tempjab;
            }
            for(i=0;i<baris;i++){
                int y = i+1;
                tbl3.setValueAt((Object)y, i, 0);
                tbl3.setValueAt((Object)nikurut[i], i, 1);
                tbl3.setValueAt((Object)namaurut[i], i, 2);
                tbl3.setValueAt((Object)jaburut[i], i, 3);
                tbl3.setValueAt((Object)rank[i], i, 4);
            }
            tabelRank.setModel(tbl3);
            String kesim = "Berikut merupakan karyawan dengan nilai tertinggi\nadalah :";
            kesim = kesim + "\n\n" + (String)tabelRank.getModel().getValueAt(0,2);
            kesimpulan.setText(kesim);
            con.close();
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_lihatActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        menuHRD menu = new menuHRD();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void divisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_divisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lihatNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lihatNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lihatNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lihatNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lihatNilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> divisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton kembali;
    private javax.swing.JTextArea kesimpulan;
    private javax.swing.JButton lihat;
    private javax.swing.JTable tabelGap;
    private javax.swing.JTable tabelNilai;
    private javax.swing.JTable tabelRank;
    // End of variables declaration//GEN-END:variables
}
