/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrdrecruitment;
import java.sql.*;
import javax.swing.*; 
import java.awt.*; 
import java.awt.event.*;
import javax.swing.table.*;
/**
 *
 * @author Galih Dea
 */
public class loginHRD extends javax.swing.JFrame {

    public static String pengguna;
    /**
     * Creates new form loginHRD
     */
    public loginHRD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        masuk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel2.setText("Username");

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel3.setText("Password");

        masuk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        masuk.setText("Masuk");
        masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clarian.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addGap(54, 54, 54))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(masuk)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukActionPerformed
        // TODO add your handling code here:
        String user = username.getText();
        String pass = new String(password.getPassword());
        
        if(user.equals("HRDC")&&pass.equals("HRDC")){
            //notif.setEnabled(true);
            //notif.setText("Login berhasil");
            pengguna = "HRDC";
            JOptionPane.showMessageDialog(null,"Login Sebagai HRD berhasil");
            menuHRD menu = new menuHRD();
            menu.setVisible(true);
            this.dispose();
        }
        else{
            if(user.equals("SPVC")&&pass.equals("SPVC")){
                pengguna = "SPVC";
                JOptionPane.showMessageDialog(null,"Login Sebagai Supervisor berhasil");
                menuHRD menu = new menuHRD();
                menu.setVisible(true);
                this.dispose();
            }
            else if (user.equals("MP")&&pass.equals("mp")){
                pengguna = "Masterbatch Plant";
                JOptionPane.showMessageDialog(null,"Login Sebagai Masterbatch Plant berhasil");
                menuHRD menu = new menuHRD();
                menu.setVisible(true);
                this.dispose();
            }
            else if (user.equals("Ma")&&pass.equals("ma")){
                pengguna = "Maintenance";
                JOptionPane.showMessageDialog(null,"Login Sebagai Maintenance berhasil");
                menuHRD menu = new menuHRD();
                menu.setVisible(true);
                this.dispose();
            }
            else if (user.equals("SA")&&pass.equals("sa")){
                pengguna = "Site Admin";
                JOptionPane.showMessageDialog(null,"Login Sebagai Site Admin berhasil");
                menuHRD menu = new menuHRD();
                menu.setVisible(true);
                this.dispose();
            }
            else if (user.equals("BB")&&pass.equals("bb")){
                pengguna = "Black Belt";
                JOptionPane.showMessageDialog(null,"Login Sebagai Black Belt berhasil");
                menuHRD menu = new menuHRD();
                menu.setVisible(true);
                this.dispose();
            }
            else if (user.equals("SA")&&pass.equals("sa")){
                pengguna = "Site Admin";
                JOptionPane.showMessageDialog(null,"Login Sebagai Site Admin berhasil");
                menuHRD menu = new menuHRD();
                menu.setVisible(true);
                this.dispose();
            }
            else if (user.equals("SE")&&pass.equals("se")){
                pengguna = "Site ESHA";
                JOptionPane.showMessageDialog(null,"Login Sebagai Site ESHA berhasil");
                menuHRD menu = new menuHRD();
                menu.setVisible(true);
                this.dispose();
            }
            else if (user.equals("Op")&&pass.equals("op")){
                pengguna = "Operation";
                JOptionPane.showMessageDialog(null,"Login Sebagai Operation berhasil");
                menuHRD menu = new menuHRD();
                menu.setVisible(true);
                this.dispose();
            }
            else if (user.equals("EX")&&pass.equals("ex")){
                pengguna = "EXIM";
                JOptionPane.showMessageDialog(null,"Login Sebagai EXIM berhasil");
                menuHRD menu = new menuHRD();
                menu.setVisible(true);
                this.dispose();
            }
            else if (user.equals("WT")&&pass.equals("wt")){
                pengguna = "Warehouse and Transportation";
                JOptionPane.showMessageDialog(null,"Login Sebagai Warehouse and Transportation berhasil");
                menuHRD menu = new menuHRD();
                menu.setVisible(true);
                this.dispose();
            }
            else if (user.equals("QC")&&pass.equals("qc")){
                pengguna = "Quality Control";
                JOptionPane.showMessageDialog(null,"Login Sebagai Quality Control berhasil");
                menuHRD menu = new menuHRD();
                menu.setVisible(true);
                this.dispose();
            }
            else if (user.equals("PP")&&pass.equals("pp")){
                pengguna = "Production Planning";
                JOptionPane.showMessageDialog(null,"Login Sebagai Production Planning berhasil");
                menuHRD menu = new menuHRD();
                menu.setVisible(true);
                this.dispose();
            }
            else if (user.equals("WW")&&pass.equals("ww")){
                pengguna = "W.W Treatment";
                JOptionPane.showMessageDialog(null,"Login Sebagai W.W Treatment berhasil");
                menuHRD menu = new menuHRD();
                menu.setVisible(true);
                this.dispose();
            }
            else if (user.equals("IM")&&pass.equals("im")){
                pengguna = "ICS MPP";
                JOptionPane.showMessageDialog(null,"Login Sebagai ICS MPP berhasil");
                menuHRD menu = new menuHRD();
                menu.setVisible(true);
                this.dispose();
            }
            else if (user.equals("SM")&&pass.equals("sm")){
                pengguna = "Site Management";
                JOptionPane.showMessageDialog(null,"Login Sebagai Site Management berhasil");
                menuHRD menu = new menuHRD();
                menu.setVisible(true);
                this.dispose();
            }
            else if (user.equals("PIP")&&pass.equals("pip")){
                pengguna = "Pigment Plant";
                JOptionPane.showMessageDialog(null,"Login Sebagai Pigment Plant berhasil");
                menuHRD menu = new menuHRD();
                menu.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null,"Login gagal");
            }
            //notif.setEnabled(true);
            //notif.setText("Login gagal");
            
        }
        
    }//GEN-LAST:event_masukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginHRD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginHRD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginHRD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginHRD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginHRD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton masuk;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
