/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrdrecruitment;
import java.sql.*;
import javax.swing.*; 
import java.awt.*; 
import java.awt.event.*;
import javax.swing.table.*;

/**
 *
 * @author Galih Dea
 */
public class nilaiHRDv2 extends javax.swing.JFrame {

    /**
     * Creates new form nilaiHRDv2
     */
    public nilaiHRDv2() {
        initComponents();
        int baris = 0;
        String keterangan = jTextArea1.getText();
        if(loginHRD.pengguna.equals("HRDC")||loginHRD.pengguna.equals("SPVC")){
            keterangan = "Keterangan Penilaian Karyawan\nDivisi "+PilihDivisi.divisyon+"\n\n"+keterangan;
        }
        else{
            keterangan = "Keterangan Penilaian Karyawan\nDivisi "+loginHRD.pengguna+"\n\n"+keterangan;
        }
        jTextArea1.setText(keterangan);
        jTextArea1.setCaretPosition(0);
        try{
            String que = "";
            //DefaultTableModel tbl = new DefaultTableModel();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hrd","root","");
            Statement stmt = con.createStatement();
            if(loginHRD.pengguna.equals("HRDC")||loginHRD.pengguna.equals("SPVC")){
                que = "select * from karyawan WHERE divisi='"+PilihDivisi.divisyon+"'";
            }
            else{
                que = "select * from karyawan WHERE divisi='"+loginHRD.pengguna+"'";
            }
            ResultSet rs = stmt.executeQuery(que);
            while(rs.next()){
                //tabelKaryawan.setValueAt();
                baris++;
            }
            con.close();
        }
        catch(Exception e){
            System.out.println(e);
        }
        try{
            String que = "";
            DefaultTableModel tbl = (DefaultTableModel)tabelNilai.getModel();
            tbl.setRowCount(baris);
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hrd","root","");
            Statement stmt = con.createStatement();
            if(loginHRD.pengguna.equals("HRDC")||loginHRD.pengguna.equals("SPVC")){
                que = "select * from karyawan WHERE divisi='"+PilihDivisi.divisyon+"'";
            }
            else{
                que = "select * from karyawan WHERE divisi='"+loginHRD.pengguna+"'";
            }
            ResultSet rs = stmt.executeQuery(que);
            int i = 0;
            while(rs.next()){
                //tabelKaryawan.setValueAt();
                int j = i+1;
                System.out.println(rs.getString(2)+","+rs.getString(3)+","+rs.getInt(4)+","+rs.getString(5)+","+rs.getString(6));
                tbl.setValueAt((Object)j,i,0);
                tbl.setValueAt((Object)rs.getString(2),i,1);
                tbl.setValueAt((Object)rs.getString(3),i,2);
                tbl.setValueAt((Object)rs.getString(6),i,3);
                i++;
            }
            tabelNilai.setModel(tbl);
        }
        catch(Exception e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel29 = new javax.swing.JLabel();
        coreSikap1 = new javax.swing.JTextField();
        secSikap1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        finSikap1 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldNIK = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldJabatan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kons = new javax.swing.JComboBox<>();
        fleks = new javax.swing.JComboBox<>();
        antis = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        penal = new javax.swing.JComboBox<>();
        kreatif = new javax.swing.JComboBox<>();
        potiq = new javax.swing.JComboBox<>();
        epsi = new javax.swing.JComboBox<>();
        ketel = new javax.swing.JComboBox<>();
        pengen = new javax.swing.JComboBox<>();
        motiv = new javax.swing.JComboBox<>();
        hatihati = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        kesop = new javax.swing.JComboBox<>();
        keped = new javax.swing.JComboBox<>();
        ketaat = new javax.swing.JComboBox<>();
        eg = new javax.swing.JComboBox<>();
        proak = new javax.swing.JComboBox<>();
        supeg = new javax.swing.JComboBox<>();
        masuk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelNilai = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelGap = new javax.swing.JTable();
        proses = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        kembali = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        carikaryawan = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelRank = new javax.swing.JTable();
        label4 = new java.awt.Label();
        coreIntelektual = new javax.swing.JTextField();
        secIntelektual = new javax.swing.JTextField();
        finIntelektual = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        coreSikap = new javax.swing.JTextField();
        secSikap = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        finSikap = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        corePerilaku = new javax.swing.JTextField();
        secPerilaku = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        finPerilaku = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Bobot Core Int");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Bobot Sec Int");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Bobot Final Int");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(252, 252, 252));

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jLabel1.setText("Penilaian Karyawan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("NIK");

        fieldNIK.setEditable(false);
        fieldNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNIKActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nama");

        fieldNama.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Jabatan");

        fieldJabatan.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Konsentrasi");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Fleksibilitas");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Antisipasi");

        kons.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        kons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konsActionPerformed(evt);
            }
        });

        fleks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        antis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Penalaran");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Kreatifitas");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Potensi IQ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Energi Psikis");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Ketelitian");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Pengendalian");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Motivasi");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Kewaspadaan");

        penal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        kreatif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        potiq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        epsi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        ketel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        pengen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        motiv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        hatihati.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Kesopanan");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Kepedulian");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Ketaatan");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Ego");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Proaktif");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Super Ego");

        kesop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        keped.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        ketaat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        eg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        proak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        supeg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        masuk.setText("Input");
        masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukActionPerformed(evt);
            }
        });

        tabelNilai.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabelNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "NIK", "Nama", "Jabatan", "Konsentrasi", "Fleksibilitas", "Antisipasi", "Penalaran", "Kreatifitas", "Potensi IQ", "Energi Psikis", "Ketelitian", "Pengendalian", "Motivasi", "Kehati-hatian", "Kesopanan", "Kepedulian", "Ketaatan", "Ego", "Proaktif", "Super Ego"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelNilai.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelNilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelNilaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelNilai);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabelGap.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabelGap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "NIK", "Nama", "Jabatan", "NCi", "NSi", "Ni", "NCsk", "NSsk", "Nsk", "NCp", "NSp", "Np", "Ha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelGap.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(tabelGap);

        proses.setText("Proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(153, 153, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\t\tINTELEKTUAL\n\nCore Factor\t\t: Konsentrasi, Fleksibilitas, dan Antisipasi\nSecondary Factor\t: Penalaran, Kreatifitas, dan Potensi IQ\n\n\t\tSIKAP\n\nCore Factor\t\t: Energi Psikis, Ketelitian, dan Pengendalian\nSecondary Factor\t: Motivasi dan Kehati-hatian\n\n\t\tPERILAKU\n\nCore Factor\t\t: Kesopanan, Kepedulian, dan Ketaatan\nSecondary Factor\t: Ego, Proaktif, dan Super Ego");
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane3.setViewportView(jTextArea1);

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("Cari NIK/Nama");

        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        label1.setText("Daftar Karyawan");

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        label2.setText("Hasil");

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        label3.setText("Keterangan");

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabelRank.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabelRank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "NIK", "Nama", "Jabatan", "Skor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabelRank);

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        label4.setText("Perhitungan");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Bobot Core Int");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Bobot Sec Int");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Bobot Final Int");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Bobot Core Sik");

        coreSikap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coreSikapActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Bobot Sec Sik");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Bobot Final Sik");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("Bobot Core Per");

        corePerilaku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corePerilakuActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("Bobot Sec Per");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setText("Bobot Final Per");

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("Intelektual");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("Sikap");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText("Perilaku");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setText("CF");

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setText("SF");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(253, 253, 253))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel38))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(34, 34, 34)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(fieldNIK, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(0, 0, Short.MAX_VALUE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(fieldJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(106, 106, 106)
                                            .addComponent(cari))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(carikaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(jLabel39)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(118, 118, 118)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(kons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(46, 46, 46)
                                        .addComponent(fleks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(44, 44, 44)
                                        .addComponent(ketel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(epsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(antis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(kreatif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                        .addComponent(potiq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(penal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel25))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(finIntelektual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                            .addComponent(secIntelektual, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(coreIntelektual, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel13)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(pengen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel15)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(hatihati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(53, 53, 53)
                                                .addComponent(motiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(39, 39, 39)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(proak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(124, 124, 124)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(eg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ketaat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(keped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(kesop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(supeg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(simpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kembali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel26)
                                                .addGap(18, 18, 18)
                                                .addComponent(coreSikap, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel27)
                                                    .addComponent(jLabel28))
                                                .addGap(20, 20, 20)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(secSikap, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                                    .addComponent(finSikap))))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel33)
                                                    .addComponent(jLabel34))
                                                .addGap(20, 20, 20)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(secPerilaku)
                                                    .addComponent(finPerilaku, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel37)
                                                    .addComponent(jLabel32))
                                                .addGap(18, 18, 18)
                                                .addComponent(corePerilaku, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel35)
                                .addGap(134, 134, 134)
                                .addComponent(jLabel36)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(proses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(masuk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fieldNama))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carikaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel35)
                                        .addGap(2, 2, 2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel36)
                                            .addComponent(jLabel37))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(kons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(epsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(masuk, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(kesop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel38)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fleks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(ketel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(keped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(proses))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(antis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(pengen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(simpan))
                            .addComponent(ketaat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel14)
                                .addComponent(eg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(motiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(penal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(kreatif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel39))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(potiq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(hatihati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(proak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel20)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(supeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kembali))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(coreIntelektual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel23))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(secIntelektual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(finIntelektual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel25))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(coreSikap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel26))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(secSikap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel27))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(finSikap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel28))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(corePerilaku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(secPerilaku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(finPerilaku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        jScrollPane5.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1074, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNIKActionPerformed

    private void konsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_konsActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        menuHRD menu = new menuHRD();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        int jumlahBaris = tabelNilai.getRowCount();
        int jumlahKolom = 17;
        int[][] data = new int[jumlahBaris][jumlahKolom];
        int i,j;
        double coreIntel = Double.parseDouble(coreIntelektual.getText());
        double secIntel = Double.parseDouble(secIntelektual.getText());
        double finIntel = Double.parseDouble(finIntelektual.getText());
        double coreSi = Double.parseDouble(coreSikap.getText());
        double secSi = Double.parseDouble(secSikap.getText());
        double finSi = Double.parseDouble(finSikap.getText());
        double corePer = Double.parseDouble(corePerilaku.getText());
        double secPer = Double.parseDouble(secPerilaku.getText());
        double finPer = Double.parseDouble(finPerilaku.getText());
        for(i=0;i<jumlahBaris;i++){
            String nik = (String)tabelNilai.getModel().getValueAt(i,1);
            for(j=0;j<jumlahKolom;j++){
                data[i][j] = Integer.parseInt((String)tabelNilai.getModel().getValueAt(i, j+4));
            }
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hrd","root","");
                String queryUpdate = "UPDATE karyawan SET konsentrasi=? , fleksibilitas=? , antisipasi=? , penalaran=? , kreatifitas=? , potensi_iq=? , energi_psikis=? , ketelitian=? , pengendalian=? , motivasi=? , kehati_hatian=? , kesopanan=? , kepedulian=? , ketaatan=? , ego=? , proaktif=? , super_ego=? , coreInt=? , secInt=? , finInt=? , coreSik=? , secSik=? , finSik=? , corePer=? , secPer=? , finPer=? WHERE nik=?";
                PreparedStatement preparedStmt = con.prepareStatement(queryUpdate);
                preparedStmt.setInt(1,data[i][0]);
                preparedStmt.setInt(2,data[i][1]);
                preparedStmt.setInt(3,data[i][2]);
                preparedStmt.setInt(4,data[i][3]);
                preparedStmt.setInt(5,data[i][4]);
                preparedStmt.setInt(6,data[i][5]);
                preparedStmt.setInt(7,data[i][6]);
                preparedStmt.setInt(8,data[i][7]);
                preparedStmt.setInt(9,data[i][8]);
                preparedStmt.setInt(10,data[i][9]);
                preparedStmt.setInt(11,data[i][10]);
                preparedStmt.setInt(12,data[i][11]);
                preparedStmt.setInt(13,data[i][12]);
                preparedStmt.setInt(14,data[i][13]);
                preparedStmt.setInt(15,data[i][14]);
                preparedStmt.setInt(16,data[i][15]);
                preparedStmt.setInt(17,data[i][16]);
                preparedStmt.setDouble(18,coreIntel);
                preparedStmt.setDouble(19,secIntel);
                preparedStmt.setDouble(20,finIntel);
                preparedStmt.setDouble(21,coreSi);
                preparedStmt.setDouble(22,secSi);
                preparedStmt.setDouble(23,finSi);
                preparedStmt.setDouble(24,corePer);
                preparedStmt.setDouble(25,secPer);
                preparedStmt.setDouble(26,finPer);
                preparedStmt.setString(27,nik);
                preparedStmt.execute();
                con.close();
                //JOptionPane.showMessageDialog(null, "Data penilaian berhasil disimpan ke database");
            }
            catch(Exception e){
                System.out.println(e);
            }
        }
        JOptionPane.showMessageDialog(null, "Data penilaian berhasil disimpan ke database");
    }//GEN-LAST:event_simpanActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbl = (DefaultTableModel)tabelGap.getModel();
        int i,j;
        int jumlahBaris = tabelNilai.getRowCount();
        tbl.setRowCount(jumlahBaris);
        int jumlahKolom = 17;
        int[][] data = new int[jumlahBaris][jumlahKolom];
        for(i=0;i<jumlahBaris;i++){
            //String nik = (String)tabelNilai.getModel().getValueAt(i,1);
            for(j=0;j<jumlahKolom;j++){
                data[i][j] = Integer.parseInt((String)tabelNilai.getModel().getValueAt(i, j+4));
            }
            /*try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hrd","root","");
                String queryUpdate = "UPDATE karyawan SET konsentrasi=? , fleksibilitas=? , antisipasi=? , penalaran=? , kreatifitas=? , potensi_iq=? , energi_psikis=? , ketelitian=? , pengendalian=? , motivasi=? , kehati_hatian=? , kesopanan=? , kepedulian=? , ketaatan=? , ego=? , proaktif=? , super_ego=? WHERE nik=?";
                PreparedStatement preparedStmt = con.prepareStatement(queryUpdate);
                preparedStmt.setInt(1,data[i][0]);
                preparedStmt.setInt(2,data[i][1]);
                preparedStmt.setInt(3,data[i][2]);
                preparedStmt.setInt(4,data[i][3]);
                preparedStmt.setInt(5,data[i][4]);
                preparedStmt.setInt(6,data[i][5]);
                preparedStmt.setInt(7,data[i][6]);
                preparedStmt.setInt(8,data[i][7]);
                preparedStmt.setInt(9,data[i][8]);
                preparedStmt.setInt(10,data[i][9]);
                preparedStmt.setInt(11,data[i][10]);
                preparedStmt.setInt(12,data[i][11]);
                preparedStmt.setInt(13,data[i][12]);
                preparedStmt.setInt(14,data[i][13]);
                preparedStmt.setInt(15,data[i][14]);
                preparedStmt.setInt(16,data[i][15]);
                preparedStmt.setInt(17,data[i][16]);
                preparedStmt.setString(18,nik);
                preparedStmt.execute();
                con.close();
            }
            catch(Exception e){
                System.out.println(e);
            }*/
        }
        double coreIntel = Double.parseDouble(coreIntelektual.getText());
        double secIntel = Double.parseDouble(secIntelektual.getText());
        double finIntel = Double.parseDouble(finIntelektual.getText());
        double coreSi = Double.parseDouble(coreSikap.getText());
        double secSi = Double.parseDouble(secSikap.getText());
        double finSi = Double.parseDouble(finSikap.getText());
        double corePer = Double.parseDouble(corePerilaku.getText());
        double secPer = Double.parseDouble(secPerilaku.getText());
        double finPer = Double.parseDouble(finPerilaku.getText());
        double[] NCi = new double[jumlahBaris];
        double[] NSi = new double[jumlahBaris];
        double[] Ni = new double[jumlahBaris];
        double[] NCsk = new double[jumlahBaris];
        double[] NSsk = new double[jumlahBaris];
        double[] Nsk = new double[jumlahBaris];
        double[] NCp = new double[jumlahBaris];
        double[] NSp = new double[jumlahBaris];
        double[] Npe = new double[jumlahBaris];
        double[] Ha = new double[jumlahBaris];
        for(i=0;i<jumlahBaris;i++){
            j = i+1;
            String nik = (String)tabelNilai.getModel().getValueAt(i,1);
            String nama = (String)tabelNilai.getModel().getValueAt(i,2);
            String jab = (String)tabelNilai.getModel().getValueAt(i,3);
            NCi[i] = (double)(data[i][0]+data[i][1]+data[i][2])/3;
            NSi[i] = (double)(data[i][3]+data[i][4]+data[i][5])/3;
            Ni[i] = (coreIntel*NCi[i])+(secIntel*NSi[i]);
            NCsk[i] = (double)(data[i][6]+data[i][7]+data[i][8])/3;
            NSsk[i] = (double)(data[i][9]+data[i][10])/2;
            Nsk[i] = (coreSi*NCsk[i])+(secSi*NSsk[i]);
            NCp[i] = (double)(data[i][11]+data[i][12]+data[i][13])/3;
            NSp[i] = (double)(data[i][14]+data[i][15]+data[i][16])/3;
            Npe[i] = (corePer*NCp[i])+(secPer*NSp[i]);
            Ha[i] = (finIntel*Ni[i])+(finSi*Nsk[i])+(finPer*Npe[i]);
            tabelGap.setValueAt((Object)j, i, 0);
            tabelGap.setValueAt((Object)nik, i, 1);
            tabelGap.setValueAt((Object)nama, i, 2);
            tabelGap.setValueAt((Object)jab, i, 3);
            tabelGap.setValueAt((Object)NCi[i], i, 4);
            tabelGap.setValueAt((Object)NSi[i], i, 5);
            tabelGap.setValueAt((Object)Ni[i], i, 6);
            tabelGap.setValueAt((Object)NCsk[i], i, 7);
            tabelGap.setValueAt((Object)NSsk[i], i, 8);
            tabelGap.setValueAt((Object)Nsk[i], i, 9);
            tabelGap.setValueAt((Object)NCp[i], i, 10);
            tabelGap.setValueAt((Object)NSp[i], i, 11);
            tabelGap.setValueAt((Object)Npe[i], i, 12);
            tabelGap.setValueAt((Object)Ha[i], i, 13);
        }
        DefaultTableModel tbel = (DefaultTableModel)tabelRank.getModel();
        tbel.setRowCount(jumlahBaris);
        String tempnik,tempnama,tempjab;
        double temprank;
        String[] nikurut = new String[jumlahBaris];
        String[] namaurut = new String[jumlahBaris];
        String[] jaburut = new String[jumlahBaris];
        double[] rank = new double[jumlahBaris];
        for(i=0;i<jumlahBaris;i++){
            nikurut[i] = (String)tabelNilai.getModel().getValueAt(i,1);
            namaurut[i] = (String)tabelNilai.getModel().getValueAt(i,2);
            jaburut[i] = (String)tabelNilai.getModel().getValueAt(i,3);
            rank[i] = Ha[i];
        }
        for(i=0;i<jumlahBaris-1;i++){
            int idxmax = i;
            for(j=i;j<jumlahBaris;j++){
                if(rank[j]>rank[idxmax]){
                    idxmax = j;
                }
            }
            temprank = rank[i];
            rank[i] = rank[idxmax];
            rank[idxmax] = temprank;
            tempnik = nikurut[i];
            nikurut[i] = nikurut[idxmax];
            nikurut[idxmax] = tempnik;
            tempnama = namaurut[i];
            namaurut[i] = namaurut[idxmax];
            namaurut[idxmax] = tempnama;
            tempjab = jaburut[i];
            jaburut[i] = jaburut[idxmax];
            jaburut[idxmax] = tempjab;
        }
        for(i=0;i<jumlahBaris;i++){
            int y = i+1;
            tabelRank.setValueAt((Object)y, i, 0);
            tabelRank.setValueAt((Object)nikurut[i], i, 1);
            tabelRank.setValueAt((Object)namaurut[i], i, 2);
            tabelRank.setValueAt((Object)jaburut[i], i, 3);
            tabelRank.setValueAt((Object)rank[i], i, 4);
        }
        JOptionPane.showMessageDialog(null, "Proses penilaian telah selesai");
    }//GEN-LAST:event_prosesActionPerformed

    private void tabelNilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelNilaiMouseClicked
        // TODO add your handling code here:
        int index = tabelNilai.getSelectedRow();
        TableModel model = tabelNilai.getModel();
        String nik = (String)model.getValueAt(index, 1);
        String nama = (String)model.getValueAt(index, 2);
        String jabatan = (String)model.getValueAt(index, 3);
        
        fieldNIK.setText(nik);
        fieldNama.setText(nama);
        fieldJabatan.setText(jabatan);
    }//GEN-LAST:event_tabelNilaiMouseClicked

    private void masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukActionPerformed
        // TODO add your handling code here:
        String nik = fieldNIK.getText();
        TableModel model = tabelNilai.getModel();
        int i;
        int indeks = 0;
        for(i=0;i<tabelNilai.getRowCount();i++){
            String nikcari = (String)model.getValueAt(i,1);
            if(nikcari.equals(nik)){
                indeks = i;
            }
        }
        tabelNilai.setValueAt((Object)kons.getSelectedItem(), indeks, 4);
        tabelNilai.setValueAt((Object)fleks.getSelectedItem(), indeks, 5);
        tabelNilai.setValueAt((Object)antis.getSelectedItem(), indeks, 6);
        tabelNilai.setValueAt((Object)penal.getSelectedItem(), indeks, 7);
        tabelNilai.setValueAt((Object)kreatif.getSelectedItem(), indeks, 8);
        tabelNilai.setValueAt((Object)potiq.getSelectedItem(), indeks, 9);
        tabelNilai.setValueAt((Object)epsi.getSelectedItem(), indeks, 10);
        tabelNilai.setValueAt((Object)ketel.getSelectedItem(), indeks, 11);
        tabelNilai.setValueAt((Object)pengen.getSelectedItem(), indeks, 12);
        tabelNilai.setValueAt((Object)motiv.getSelectedItem(), indeks, 13);
        tabelNilai.setValueAt((Object)hatihati.getSelectedItem(), indeks, 14);
        tabelNilai.setValueAt((Object)kesop.getSelectedItem(), indeks, 15);
        tabelNilai.setValueAt((Object)keped.getSelectedItem(), indeks, 16);
        tabelNilai.setValueAt((Object)ketaat.getSelectedItem(), indeks, 17);
        tabelNilai.setValueAt((Object)eg.getSelectedItem(), indeks, 18);
        tabelNilai.setValueAt((Object)proak.getSelectedItem(), indeks, 19);
        tabelNilai.setValueAt((Object)supeg.getSelectedItem(), indeks, 20);
        JOptionPane.showMessageDialog(null,"Penilaian karyawan berhasil ditambahkan");
        balikKeSemula();
    }//GEN-LAST:event_masukActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        String kunci = carikaryawan.getText();
        kunci = kunci.toLowerCase();
        int baris = tabelNilai.getRowCount();
        int i;
        int ketemu = 0;
        
        for(i=0;i<baris;i++){
            String nik = (String)tabelNilai.getModel().getValueAt(i,1);
            String nama = (String)tabelNilai.getModel().getValueAt(i,2);
            nik = nik.toLowerCase();
            nama = nama.toLowerCase();
            if(nik.contains(kunci)||nama.contains(kunci)){
                ketemu++;
            }
        }
        if(ketemu==0){
            JOptionPane.showMessageDialog(null, "NIK atau nama yang dicari tidak ditemukan");
        }
        else{
            JOptionPane.showMessageDialog(null, "NIK atau nama yang dicari ditemukan");
            if(ketemu==1){
                int arr = 0;
                for(i=0;i<baris;i++){
                    String nik = (String)tabelNilai.getModel().getValueAt(i,1);
                    String nama = (String)tabelNilai.getModel().getValueAt(i,2);
                    nik = nik.toLowerCase();
                    nama = nama.toLowerCase();
                    if(nik.contains(kunci)||nama.contains(kunci)){
                        arr = i;
                    }
                }
                tukarBaris(0,arr);
            }
            else{
                int arrIndex[] = new int[ketemu];
                int j = 0;
                for(i=0;i<baris;i++){
                    String nik = (String)tabelNilai.getModel().getValueAt(i,1);
                    String nama = (String)tabelNilai.getModel().getValueAt(i,2);
                    nik = nik.toLowerCase();
                    nama = nama.toLowerCase();
                    if(nik.contains(kunci)||nama.contains(kunci)){
                        arrIndex[j] = i;
                        j++;
                    }
                }
                int z;
                for(z=0;z<ketemu;z++){
                    tukarBaris(z,arrIndex[z]);
                }
            }
        }
    }//GEN-LAST:event_cariActionPerformed

    private void coreSikapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coreSikapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coreSikapActionPerformed

    private void corePerilakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corePerilakuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corePerilakuActionPerformed

    private void tukarBaris(int i,int j){
        String nik = (String)tabelNilai.getModel().getValueAt(i,1);
        String nama = (String)tabelNilai.getModel().getValueAt(i,2);
        String jabatan = (String)tabelNilai.getModel().getValueAt(i,3);
        String konsen = (String)tabelNilai.getModel().getValueAt(i,4);
        String fleksi = (String)tabelNilai.getModel().getValueAt(i,5);
        String antisip = (String)tabelNilai.getModel().getValueAt(i,6);
        String penalar = (String)tabelNilai.getModel().getValueAt(i,7);
        String kreati = (String)tabelNilai.getModel().getValueAt(i,8);
        String poteniq = (String)tabelNilai.getModel().getValueAt(i,9);
        String energips = (String)tabelNilai.getModel().getValueAt(i,10);
        String keteli = (String)tabelNilai.getModel().getValueAt(i,11);
        String kendal = (String)tabelNilai.getModel().getValueAt(i,12);
        String motiva = (String)tabelNilai.getModel().getValueAt(i,13);
        String kehat = (String)tabelNilai.getModel().getValueAt(i,14);
        String sopan = (String)tabelNilai.getModel().getValueAt(i,15);
        String pedul = (String)tabelNilai.getModel().getValueAt(i,16);
        String taat = (String)tabelNilai.getModel().getValueAt(i,17);
        String egoo = (String)tabelNilai.getModel().getValueAt(i,18);
        String proa = (String)tabelNilai.getModel().getValueAt(i,19);
        String supego = (String)tabelNilai.getModel().getValueAt(i,20);
        String tempnik = (String)tabelNilai.getModel().getValueAt(j,1);
        String tempnama = (String)tabelNilai.getModel().getValueAt(j,2);
        String tempjabatan = (String)tabelNilai.getModel().getValueAt(j,3);
        String tempkonsen = (String)tabelNilai.getModel().getValueAt(j,4);
        String tempfleksi = (String)tabelNilai.getModel().getValueAt(j,5);
        String tempantisip = (String)tabelNilai.getModel().getValueAt(j,6);
        String temppenalar = (String)tabelNilai.getModel().getValueAt(j,7);
        String tempkreati = (String)tabelNilai.getModel().getValueAt(j,8);
        String temppoteniq = (String)tabelNilai.getModel().getValueAt(j,9);
        String tempenergips = (String)tabelNilai.getModel().getValueAt(j,10);
        String tempketeli = (String)tabelNilai.getModel().getValueAt(j,11);
        String tempkendal = (String)tabelNilai.getModel().getValueAt(j,12);
        String tempmotiva = (String)tabelNilai.getModel().getValueAt(j,13);
        String tempkehat = (String)tabelNilai.getModel().getValueAt(j,14);
        String tempsopan = (String)tabelNilai.getModel().getValueAt(j,15);
        String temppedul = (String)tabelNilai.getModel().getValueAt(j,16);
        String temptaat = (String)tabelNilai.getModel().getValueAt(j,17);
        String tempegoo = (String)tabelNilai.getModel().getValueAt(j,18);
        String tempproa = (String)tabelNilai.getModel().getValueAt(j,19);
        String tempsupego = (String)tabelNilai.getModel().getValueAt(j,20);
        tabelNilai.setValueAt((Object)nik, j, 1);
        tabelNilai.setValueAt((Object)nama, j, 2);
        tabelNilai.setValueAt((Object)jabatan, j, 3);
        tabelNilai.setValueAt((Object)konsen, j, 4);
        tabelNilai.setValueAt((Object)fleksi, j, 5);
        tabelNilai.setValueAt((Object)antisip, j, 6);
        tabelNilai.setValueAt((Object)penalar, j, 7);
        tabelNilai.setValueAt((Object)kreati, j, 8);
        tabelNilai.setValueAt((Object)poteniq, j, 9);
        tabelNilai.setValueAt((Object)energips, j, 10);
        tabelNilai.setValueAt((Object)keteli, j, 11);
        tabelNilai.setValueAt((Object)kendal, j, 12);
        tabelNilai.setValueAt((Object)motiva, j, 13);
        tabelNilai.setValueAt((Object)kehat, j, 14);
        tabelNilai.setValueAt((Object)sopan, j, 15);
        tabelNilai.setValueAt((Object)pedul, j, 16);
        tabelNilai.setValueAt((Object)taat, j, 17);
        tabelNilai.setValueAt((Object)egoo, j, 18);
        tabelNilai.setValueAt((Object)proa, j, 19);
        tabelNilai.setValueAt((Object)supego, j, 20);
        tabelNilai.setValueAt((Object)tempnik, i, 1);
        tabelNilai.setValueAt((Object)tempnama, i, 2);
        tabelNilai.setValueAt((Object)tempjabatan, i, 3);
        tabelNilai.setValueAt((Object)tempkonsen, i, 4);
        tabelNilai.setValueAt((Object)tempfleksi, i, 5);
        tabelNilai.setValueAt((Object)tempantisip, i, 6);
        tabelNilai.setValueAt((Object)temppenalar, i, 7);
        tabelNilai.setValueAt((Object)tempkreati, i, 8);
        tabelNilai.setValueAt((Object)temppoteniq, i, 9);
        tabelNilai.setValueAt((Object)tempenergips, i, 10);
        tabelNilai.setValueAt((Object)tempketeli, i, 11);
        tabelNilai.setValueAt((Object)tempkendal, i, 12);
        tabelNilai.setValueAt((Object)tempmotiva, i, 13);
        tabelNilai.setValueAt((Object)tempkehat, i, 14);
        tabelNilai.setValueAt((Object)tempsopan, i, 15);
        tabelNilai.setValueAt((Object)temppedul, i, 16);
        tabelNilai.setValueAt((Object)temptaat, i, 17);
        tabelNilai.setValueAt((Object)tempegoo, i, 18);
        tabelNilai.setValueAt((Object)tempproa, i, 19);
        tabelNilai.setValueAt((Object)tempsupego, i, 20);
    }
    
    private void balikKeSemula(){
        fieldNIK.setText("");
        fieldNama.setText("");
        fieldJabatan.setText("");
        kons.setSelectedIndex(0);
        fleks.setSelectedIndex(0);
        antis.setSelectedIndex(0);
        penal.setSelectedIndex(0);
        kreatif.setSelectedIndex(0);
        potiq.setSelectedIndex(0);
        epsi.setSelectedIndex(0);
        ketel.setSelectedIndex(0);
        pengen.setSelectedIndex(0);
        motiv.setSelectedIndex(0);
        hatihati.setSelectedIndex(0);
        kesop.setSelectedIndex(0);
        keped.setSelectedIndex(0);
        ketaat.setSelectedIndex(0);
        eg.setSelectedIndex(0);
        proak.setSelectedIndex(0);
        supeg.setSelectedIndex(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nilaiHRDv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nilaiHRDv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nilaiHRDv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nilaiHRDv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nilaiHRDv2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> antis;
    private javax.swing.JButton cari;
    private javax.swing.JTextField carikaryawan;
    private javax.swing.JTextField coreIntelektual;
    private javax.swing.JTextField corePerilaku;
    private javax.swing.JTextField coreSikap;
    private javax.swing.JTextField coreSikap1;
    private javax.swing.JComboBox<String> eg;
    private javax.swing.JComboBox<String> epsi;
    private javax.swing.JTextField fieldJabatan;
    private javax.swing.JTextField fieldNIK;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JTextField finIntelektual;
    private javax.swing.JTextField finPerilaku;
    private javax.swing.JTextField finSikap;
    private javax.swing.JTextField finSikap1;
    private javax.swing.JComboBox<String> fleks;
    private javax.swing.JComboBox<String> hatihati;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton kembali;
    private javax.swing.JComboBox<String> keped;
    private javax.swing.JComboBox<String> kesop;
    private javax.swing.JComboBox<String> ketaat;
    private javax.swing.JComboBox<String> ketel;
    private javax.swing.JComboBox<String> kons;
    private javax.swing.JComboBox<String> kreatif;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JButton masuk;
    private javax.swing.JComboBox<String> motiv;
    private javax.swing.JComboBox<String> penal;
    private javax.swing.JComboBox<String> pengen;
    private javax.swing.JComboBox<String> potiq;
    private javax.swing.JComboBox<String> proak;
    private javax.swing.JButton proses;
    private javax.swing.JTextField secIntelektual;
    private javax.swing.JTextField secPerilaku;
    private javax.swing.JTextField secSikap;
    private javax.swing.JTextField secSikap1;
    private javax.swing.JButton simpan;
    private javax.swing.JComboBox<String> supeg;
    private javax.swing.JTable tabelGap;
    private javax.swing.JTable tabelNilai;
    private javax.swing.JTable tabelRank;
    // End of variables declaration//GEN-END:variables
}
