/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrdrecruitment;

/**
 *
 * @author Galih Dea
 */
public class PilihDivisi extends javax.swing.JFrame {

    /**
     * Creates new form PilihDivisi
     */
    public static String divisyon;
    
    public PilihDivisi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        siman = new javax.swing.JButton();
        master = new javax.swing.JButton();
        pigpla = new javax.swing.JButton();
        wt = new javax.swing.JButton();
        siad = new javax.swing.JButton();
        blabe = new javax.swing.JButton();
        exim = new javax.swing.JButton();
        oper = new javax.swing.JButton();
        mainte = new javax.swing.JButton();
        wwt = new javax.swing.JButton();
        icsm = new javax.swing.JButton();
        sesha = new javax.swing.JButton();
        propel = new javax.swing.JButton();
        qc = new javax.swing.JButton();
        tombolKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(589, 634));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel1.setText("Divisi");

        siman.setText("Site Management");
        siman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simanActionPerformed(evt);
            }
        });

        master.setText("Masterbatch Plant");
        master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterActionPerformed(evt);
            }
        });

        pigpla.setText("Pigment Plant");
        pigpla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pigplaActionPerformed(evt);
            }
        });

        wt.setText("W & T");
        wt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wtActionPerformed(evt);
            }
        });

        siad.setText("Site Admin");
        siad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siadActionPerformed(evt);
            }
        });

        blabe.setText("Black Belt");
        blabe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blabeActionPerformed(evt);
            }
        });

        exim.setText("EXIM");
        exim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eximActionPerformed(evt);
            }
        });

        oper.setText("Operation");
        oper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operActionPerformed(evt);
            }
        });

        mainte.setText("Maintenance");
        mainte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainteActionPerformed(evt);
            }
        });

        wwt.setText("W.W Treatment");
        wwt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wwtActionPerformed(evt);
            }
        });

        icsm.setText("ICS MPP");
        icsm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icsmActionPerformed(evt);
            }
        });

        sesha.setText("Site ESHA");
        sesha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seshaActionPerformed(evt);
            }
        });

        propel.setText("Production Planning");
        propel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propelActionPerformed(evt);
            }
        });

        qc.setText("QC");
        qc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qcActionPerformed(evt);
            }
        });

        tombolKembali.setText("Kembali");
        tombolKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tombolKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(mainte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pigpla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(master, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(blabe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(propel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(icsm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(wt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(oper, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sesha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(siad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(siman, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(wwt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 135, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(master)
                    .addComponent(siman))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wwt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pigpla))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainte)
                    .addComponent(siad))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blabe)
                    .addComponent(sesha))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(propel)
                    .addComponent(oper))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qc)
                    .addComponent(wt))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icsm)
                    .addComponent(exim))
                .addGap(18, 18, 18)
                .addComponent(tombolKembali)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simanActionPerformed
        // TODO add your handling code here:
        divisyon = "Site Management";
        redir();
    }//GEN-LAST:event_simanActionPerformed

    private void masterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterActionPerformed
        // TODO add your handling code here:
        divisyon = "Masterbatch Plant";
        redir();
    }//GEN-LAST:event_masterActionPerformed

    private void pigplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pigplaActionPerformed
        // TODO add your handling code here:
        divisyon = "Pigment Plant";
        redir();
    }//GEN-LAST:event_pigplaActionPerformed

    private void mainteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainteActionPerformed
        // TODO add your handling code here:
        divisyon = "Maintenance";
        redir();
    }//GEN-LAST:event_mainteActionPerformed

    private void siadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siadActionPerformed
        // TODO add your handling code here:
        divisyon = "Site Admin";
        redir();
    }//GEN-LAST:event_siadActionPerformed

    private void blabeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blabeActionPerformed
        // TODO add your handling code here:
        divisyon = "Black Belt";
        redir();
    }//GEN-LAST:event_blabeActionPerformed

    private void seshaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seshaActionPerformed
        // TODO add your handling code here:
        divisyon = "Site ESHA";
        redir();
    }//GEN-LAST:event_seshaActionPerformed

    private void operActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operActionPerformed
        // TODO add your handling code here:
        divisyon = "Operation";
        redir();
    }//GEN-LAST:event_operActionPerformed

    private void propelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propelActionPerformed
        // TODO add your handling code here:
        divisyon = "Production Planning";
        redir();
    }//GEN-LAST:event_propelActionPerformed

    private void wwtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wwtActionPerformed
        // TODO add your handling code here:
        divisyon = "W.W Treatment";
        redir();
    }//GEN-LAST:event_wwtActionPerformed

    private void icsmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icsmActionPerformed
        // TODO add your handling code here:
        divisyon = "ICS MPP";
        redir();
    }//GEN-LAST:event_icsmActionPerformed

    private void eximActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eximActionPerformed
        // TODO add your handling code here:
        divisyon = "EXIM";
        redir();
    }//GEN-LAST:event_eximActionPerformed

    private void wtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wtActionPerformed
        // TODO add your handling code here:
        divisyon = "Warehouse and Transportation";
        redir();
    }//GEN-LAST:event_wtActionPerformed

    private void qcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qcActionPerformed
        // TODO add your handling code here:
        divisyon = "Quality Control";
        redir();
    }//GEN-LAST:event_qcActionPerformed

    private void tombolKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKembaliActionPerformed
        // TODO add your handling code here:
        menuHRD rumah = new menuHRD();
        rumah.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolKembaliActionPerformed
    
    private void redir(){
        nilaiHRDv2 nila = new nilaiHRDv2();
        nila.setVisible(true);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihDivisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihDivisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihDivisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihDivisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihDivisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blabe;
    private javax.swing.JButton exim;
    private javax.swing.JButton icsm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mainte;
    private javax.swing.JButton master;
    private javax.swing.JButton oper;
    private javax.swing.JButton pigpla;
    private javax.swing.JButton propel;
    private javax.swing.JButton qc;
    private javax.swing.JButton sesha;
    private javax.swing.JButton siad;
    private javax.swing.JButton siman;
    private javax.swing.JButton tombolKembali;
    private javax.swing.JButton wt;
    private javax.swing.JButton wwt;
    // End of variables declaration//GEN-END:variables
}
